### ISSUE TITLE
Liskov Substitution Principle and type-checking

### ISSUE THREAD

**Issue by rey0bs** [jupeter/clean-code-php#46] opened 2017-09-01 07:57 UTC
Hi,
There is a type-checking in Liskov Substitution Principle good example.
But type-checking is declared before like a bad practice.

PS : Thanks for this very good resource :)

**Comment by peter-gribanov** [comment] 2017-09-01 16:53
This is a duplicate of #37

**Comment by TomasVotruba** [comment] 2017-09-03 22:51
Hi @Saimount, we're glad you find it useful :)

I'm closing this in favor of mentioned existing issue.
Could you send PR with fix for that?

**Closed as completed by TomasVotruba** 2017-09-03 22:51 UTC
