### ISSUE TITLE
Disagree about: `Function arguments (2 or fewer ideally)`

### ISSUE THREAD

**Issue by damianopetrungaro** [jupeter/clean-code-php#151] opened 2018-07-02 12:09 UTC
I don't really believe that this is always a best practice.

IMHO the most of the cases are better to be explicit about all the dependencies needed by an object to be created, avoiding to created object in an invalid state.

Creating only valid object will reduce the amount of `if ($object->getProperty() !== null)` and will help you to better focus on the domain.

If the creation of an object is "hard" you can use a factory/builder to make it easier to interact with, but it will ALWAYS create an object in a valid state.

**Comment by peter-gribanov** [comment] 2019-07-12 07:39
I finally understood the problem with this example.

The problem is that it is transferred from [JavaScript](https://github.com/ryanmcdermott/clean-code-javascript#function-arguments-2-or-fewer-ideally) to [PHP](https://github.com/jupeter/clean-code-php#function-arguments-2-or-fewer-ideally) as it is, without adaptation.
The problem is that in different languages the same function behaves differently.

```js
function createMenu(title, body, buttonText, cancellable) {
  console.log(title, body, buttonText, cancellable);
}
createMenu();
// print
// undefined undefined undefined undefined undefined
```
Test this: https://jsfiddle.net/ghost404/takjuLcx/1/
```php
function createMenu($title, $body, $buttonText, $cancellable)
{
    var_dump($title);
    var_dump($body);
    var_dump($buttonText);
    var_dump($cancellable);
}
createMenu();
// error on execution
// Fatal error: Uncaught ArgumentCountError: Too few arguments to function createMenu(), 0 passed in /in/EOfKM on line 10 and exactly 4 expected
```
Test this: https://3v4l.org/EOfKM

In JavaScript, function arguments are always optional, and their presence is already checked in the function itself. In PHP need to explicitly indicate that the arguments are not required.

If in JavaScript the packing of optional arguments in the DTO is normal, then in PHP the packing of the required arguments in the DTO is not equivalent. **This is really a mistake.**

**Closed as completed** 2019-09-12 08:30 UTC
